# Generated by Django 4.0.2 on 2022-02-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220205_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membeship',
            new_name='membership',
        ),
    ]
